/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package git_test;

public class Library {
    public boolean someLibraryMethod() {
    	// push hatjana!!
    	// push hatjana!!
    	// push hatjana!!
    	// push hatjana!!
    	// push hatjana!!
        return true;
    }
}
